// File generated by `flutterfire configure`.
// This file contains platform-specific Firebase configuration.
// Do not edit this file manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GYFpTXz3GP9hxR1sSQqx1LvZRC2pErg',
    appId: '1:886123571251:android:e3a0ba4779963c23de5b46',
    messagingSenderId: '886123571251',
    projectId: 'mobile-ai-helpdesk-4b668',
    storageBucket: 'mobile-ai-helpdesk-4b668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmqZx9k4GZZXz1L7QZMqj5NvL2NvL6gJ8',
    appId: '1:886123571251:ios:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '886123571251',
    projectId: 'mobile-ai-helpdesk-4b668',
    storageBucket: 'mobile-ai-helpdesk-4b668.firebasestorage.app',
    iosBundleId: 'com.jarvis.helpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmqZx9k4GZZXz1L7QZMqj5NvL2NvL6gJ8',
    appId: '1:886123571251:macos:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '886123571251',
    projectId: 'mobile-ai-helpdesk-4b668',
    storageBucket: 'mobile-ai-helpdesk-4b668.firebasestorage.app',
    iosBundleId: 'com.jarvis.helpdesk.macos',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7GYFpTXz3GP9hxR1sSQqx1LvZRC2pErg',
    appId: '1:886123571251:web:a1b2c3d4e5f6g7h8i9j0k1l2',
    messagingSenderId: '886123571251',
    projectId: 'mobile-ai-helpdesk-4b668',
    authDomain: 'mobile-ai-helpdesk-4b668.firebaseapp.com',
    storageBucket: 'mobile-ai-helpdesk-4b668.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7GYFpTXz3GP9hxR1sSQqx1LvZRC2pErg',
    appId: '1:886123571251:windows:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '886123571251',
    projectId: 'mobile-ai-helpdesk-4b668',
    storageBucket: 'mobile-ai-helpdesk-4b668.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC7GYFpTXz3GP9hxR1sSQqx1LvZRC2pErg',
    appId: '1:886123571251:linux:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '886123571251',
    projectId: 'mobile-ai-helpdesk-4b668',
    storageBucket: 'mobile-ai-helpdesk-4b668.firebasestorage.app',
  );
}
