// File generated by FlutterFire CLI (run: dart run flutterfire_cli:flutterfire configure).
// Replace this placeholder with your real config from Firebase Console.
// See docs/FIREBASE_ANALYTICS_SETUP.md for setup steps.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:xxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:xxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:000000000000:ios:xxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    iosBundleId: 'com.jarvis.helpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:000000000000:ios:xxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    iosBundleId: 'com.jarvis.helpdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:000000000000:web:xxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    measurementId: 'G-XXXXXXXXXX',
  );
}
