// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBV-U6MiUcAqiP2KTe5QNidiSRt_9PpM',
    appId: '1:787965887352:web:eb5c1721c0f0cf374cbe8d',
    messagingSenderId: '787965887352',
    projectId: 'mobile-ai-helpdesk',
    authDomain: 'mobile-ai-helpdesk.firebaseapp.com',
    storageBucket: 'mobile-ai-helpdesk.firebasestorage.app',
    measurementId: 'G-LW9E5DZLDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHT_ojHOhWdTuivTXcewlvcorV-5YNjio',
    appId: '1:787965887352:android:1efc42481970bd784cbe8d',
    messagingSenderId: '787965887352',
    projectId: 'mobile-ai-helpdesk',
    storageBucket: 'mobile-ai-helpdesk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhnyciGpiw5TXPlVO2RO7l005F9MulXY',
    appId: '1:787965887352:ios:026fd6afd5571d584cbe8d',
    messagingSenderId: '787965887352',
    projectId: 'mobile-ai-helpdesk',
    storageBucket: 'mobile-ai-helpdesk.firebasestorage.app',
    iosBundleId: 'com.jarvis.helpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhnyciGpiw5TXPlVO2RO7l005F9MulXY',
    appId: '1:787965887352:ios:ebbe2b7981373fa74cbe8d',
    messagingSenderId: '787965887352',
    projectId: 'mobile-ai-helpdesk',
    storageBucket: 'mobile-ai-helpdesk.firebasestorage.app',
    iosBundleId: 'com.example.aiHelpdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYBV-U6MiUcAqiP2KTe5QNidiSRt_9PpM',
    appId: '1:787965887352:web:a76b153c0411200e4cbe8d',
    messagingSenderId: '787965887352',
    projectId: 'mobile-ai-helpdesk',
    authDomain: 'mobile-ai-helpdesk.firebaseapp.com',
    storageBucket: 'mobile-ai-helpdesk.firebasestorage.app',
    measurementId: 'G-7K5TYG85J9',
  );
}
